### ISSUE TITLE
1.3.2 Functional Requirements

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#15]
1. Task title ID: #15
2. What is the task about? Please describe in detail.
The task involves defining and documenting the functional requirements for a web-based system that manages staff workload planning and allocation for a company. The system will have specific functionalities for both managers and employees, ensuring efficient job allocation and workload management.

3. What are the goals of the task? Please describe in detail.

- To clearly specify the functional requirements for the system, including those for general system functionality, manager-specific features, employee-specific features, workload planning, allocation rules, and data storage.

- To provide a comprehensive and detailed description of how the system should behave, ensuring that all stakeholders understand what is expected from the system.

- To establish a foundation for the development team to design, build, and test the system according to the defined requirements.

4. Success or completion criteria. Please describe in detail.
The task will be considered successfully completed when the following criteria are met:

- All functional requirements have been clearly and accurately documented, leaving no ambiguity about the system's expected behavior.

- The requirements are organized into logical sections, making it easy for stakeholders and the development team to reference and understand.

- The document includes any necessary explanations, constraints, or dependencies associated with each requirement.

- The document is reviewed and approved by relevant stakeholders, including IT administrators, managers, and employees, to ensure alignment with their needs and expectations.

The document is readily available for reference during the development process and any future updates or modifications.

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 15th September 2023
End Date: 19th September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Marhakim (mdmarhakim)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
Issue / Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by mdmarhakim** [comment]
NA

**Comment by mdmarhakim** [comment]
Describe the work done in detail.

All functional requirements (FR1 to FR17) have been clearly and accurately documented, leaving no ambiguity about the system's expected behavior.

The requirements are organized into logical sections, making it easy for stakeholders and the development team to reference and understand.

The document includes any necessary explanations, constraints, or dependencies associated with each requirement.

Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?
The document is readily available for reference during the development process and any future updates or modifications.

Start date and end date of the work done
Start Date: 15th September 2023
End Date: 19th September 2023
